# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
#  push:
#    branches:
#      - master 
#      - testing
#  pull_request:
#    branches: 
#      - master 
#      - testing

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Test on ${{ matrix.os }}
      run: |
        ./test_std.sh --debug --verbose --foo bar 
        ./test_parsers.sh --debug --verbose --foo bar
